<?php
$view = $this->view;
$uid = $this->uid;
?>
<?php if ($view == "submit"): ?>
    <div class="simpleBox">
        <ul class="simpleBoxLi">
            <li>
                <h3>Change Password</h3>
                <p>Fill in your credential below, we will email you the instructions to change your password.</p>
            </li>
            <li>
                <form id="forgotPasswordSubmitForm" action="mailsent" method="get">
                    <table class="simpleBoxTable">
                        <tr>
                            <td><label for="forgotPasswordEmail">Email</label></td>
                            <td>
                                <input name="forgotPasswordEmail" type="email" class="simpleBoxTextInput" required="true">
                                <label for="forgotPasswordEmail" class="validation_err_msg error" generated="true"></label>
                            </td>
                        </tr>
                    </table>
                </form>
            </li>
            <li><span id="forgotPasswordSubmitButton" class="simpleBoxButton">Submit</span></li>
        </ul>
    </div>
<?php elseif ($view == "change"): ?>
    <div class="simpleBox">
        <ul class="simpleBoxLi">
            <li>
                <form id="forgotPasswordChangeForm" action="changepassword" method="post">
                    <input type="hidden" name="forgotPasswordUid" value="<?= $uid ?>">
                    <table>
                        <tr>
                            <td><label>New Password</label></td>
                            <td>
                                <input id="forgotPasswordNewPassword" name="forgotPasswordNewPassword" type="password" class="simpleBoxTextInput" required="true" minlength="6" maxlength="20" nowhitespace="true">
                                <label for="forgotPasswordNewPassword" class="validation_err_msg error" generated="true"></label>
                            </td>
                        </tr>
                        <tr>
                            <td><label>Confirm New Password</label></td>
                            <td>
                                <input id="forgotPasswordConfirmNewPassword" name="forgotPasswordConfirmNewPassword" type="password" class="simpleBoxTextInput" required="true" equalTo="#forgotPasswordNewPassword">
                                <label for="forgotPasswordConfirmNewPassword" class="validation_err_msg error" generated="true"></label>
                            </td>
                        </tr>
                    </table>
                </form>
            </li>
            <li><span id="forgotPasswordChangeButton" class="simpleBoxButton">Confirm</span></li>
        </ul>
    </div>
<?php elseif ($view == "errors"): ?>
<h3>Invalid parameters</h3>
<?php endif; ?>
