<div class="simpleBox reg_form">
    <h3>Register - Welcome To Our Family!</h3>
    <hr>
    <p>You can sign in directly with your facebook account</p>
    <img src="<?= ROOT_URI . "/images/mslc/facebookLogin.jpg" ?>" onclick="Facebook_login()" style="cursor: pointer">
    <div>
        <h3>OR</h3>
        <p>Sign up manually</p>
        <form id="regForm" name="reg" action="" method="post">
            <table class="regTable">
                <tr>
                    <td>
                        Email: 
                    </td>
                    <td>
                        <input type="email" name="regEmail" id="regEmail" class="simpleBoxTextInput" required="true">
                        <label for="regEmail" class="validation_err_msg error" generated="true"></label>
                        <label id="regEmailError" class="validation_err_msg error"></label>
                    </td>
                    <td>
                        <img class="profileEditQuestionMark" src="<?= ROOT_URI . "/images/mslc/questionMark.jpg" ?>">
                        <span class="simpleBoxTooltip">Please enter your primary email address.</span>
                    </td>
                </tr>
                <tr>
                    <td>
                        Password:
                    </td>
                    <td>
                        <input type="password" name="regPassword" class="simpleBoxTextInput" required="true" minlength="6" maxlength="20" nowhitespace="true">
                        <label for="regPassword" class="validation_err_msg error" generated="true"></label>
                    </td>
                    <td>
                        <img class="profileEditQuestionMark" src="<?= ROOT_URI . "/images/mslc/questionMark.jpg" ?>">
                        <span class="simpleBoxTooltip">Choose your preferred sign in pass.</span>
                    </td>
                </tr>
                <tr>
                    <td>
                        Preferred Nick:
                    </td>
                    <td>
                        <input type="text" name="regNick" class="simpleBoxTextInput" required="true" alphanumeric="true" maxlength="20" minlength="5" nowhitespace="true">
                        <label for="regNick" class="validation_err_msg error" generated="true"></label>
                    </td>
                    <td>
                        <img class="profileEditQuestionMark" src="<?= ROOT_URI . "/images/mslc/questionMark.jpg" ?>">
                        <span class="simpleBoxTooltip">Choose a nickname to display to the public.</span>
                    </td>
                </tr>
                <tr>
                    <td columnspan="3">
                        <span class="simpleBoxButton" id="regSubmitButton">Submit</span>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>