<?= $this->doctype(); ?>
<html lang="en">
    <head> 
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />  
        <title>Iknowu.com</title> 
        <?php ChromePhp::log(get_class($this)) ?>
        <?= $this->cssHelper() ?>    
        <?= $this->javascriptHelper() ?>  
    </script>
</head>
<body>
    <!--
    <div id="fb-root"></div>
    <script>
        _initFacebook();
    </script>
    -->
    <div id="fb-root"></div>
    <script>
        window.fbAsyncInit = function() {
            // init the FB JS SDK
            FB.init({
                appId      : '402938169774921', // App ID from the App Dashboard
                channelUrl : '//localhost/iknowu/public/channel.php', // Channel File for x-domain communication
                status     : false, // check the login status upon init?
                cookie     : true, // set sessions cookies to allow your server to access the session?
                xfbml      : false,  // parse XFBML tags on this page?
                oauth      : true,
                debug      : true
            });

            // Additional initialization code such as adding Event Listeners goes here

        };

        // Load the SDK's source Asynchronously
        // Note that the debug version is being actively developed and might 
        // contain some type checks that are overly strict. 
        // Please report such bugs using the bugs tool.
        (function(d, debug){
            var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
            if (d.getElementById(id)) {return;}
            js = d.createElement('script'); js.id = id; js.async = true;
            js.src = "//connect.facebook.net/en_US/all" + (debug ? "/debug" : "") + ".js";
            ref.parentNode.insertBefore(js, ref);
        }(document, /*debug*/ false));
    </script>
    <div class="headerContainerOuter">
        <div class="headerContainer"> 
            <header class="header">
                <?php require_once("header.phtml") ?>
            </header>
        </div>

        <div class="naviContainer">
            <nav>
                <?php require_once("navi.phtml") ?>
            </nav>
        </div>
    </div>
    <div class="bodyContainer"> 
        <article class="content">
            <div class="articleContainerDiv">
                <?php echo $this->layout()->content; ?>
            </div>
        </article>
        <footer class="footer">
            <?php require_once("footer.phtml") ?>
        </footer>
    </div>
</body>
</html>