<!-- navigation -->
<div class="naviContainerDiv">
        <ul class="navi">
            <li><a href="<?= $this->url(array("controller" => "index", "action" => "index")); ?>" target="_self">TRENDING</a></li>
            <li><a href="<?= $this->url(array("controller" => "about", "action" => "index")); ?>" target="_self">ABOUT</a></li>
            <li><a href="<?= $this->url(array("controller" => "product", "action" => "upload")); ?>"><strong>I WANT 2 SELL</strong></a></li>
            <li><a href="<?= $this->url(array("controller" => "feedback", "action" => "index")); ?>" target="_self">FEEDBACK</a></li>
        </ul>
</div>