<div class="simpleBox" style="width: 700px;">
    <form action="" method="post" name="editPasswordForm" id="editPasswordForm">
        <table class="profileEditPasswordTable">
            <tr>
                <td>Current Password:</td>
                <td>
                    <input name="currPwd" id="currPwd" class="profileEditTextInput" type="password" value="<?= $this->currentPassword ?>" />
                    <div class="validation_err_msg"><?= $this->currPwdErr ?></div>
                </td>
                <td>
                    <img class="profileEditQuestionMark" src="<?= ROOT_URI . "/images/mslc/questionMark.jpg" ?>">
                    <span class="simpleBoxTooltip">Please enter your current password.</span>
                </td>
            </tr>
            <tr>
                <td>New Password:</td>
                <td>
                    <input name="newPwd" id="newPwd" class="profileEditTextInput" type="password" value="<?= $this->newPassword ?>" />
                    <div class="validation_err_msg"><?= $this->newPwdErr ?></div>
                </td>
                <td>
                    <img class="profileEditQuestionMark" src="<?= ROOT_URI . "/images/mslc/questionMark.jpg" ?>">
                    <span class="simpleBoxTooltip">Please enter your new password.</span>
                </td>
            </tr>
            <tr>
                <td>Confirm New Password:</td>
                <td>
                    <input name="conNewPwd" id="conNewPwd" class="profileEditTextInput" type="password" value="<?= $this->confirmNewPassword ?>" />
                    <div class="validation_err_msg"><?= $this->conNewPwdErr ?></div>
                </td>
                <td>
                    <img class="profileEditQuestionMark" src="<?= ROOT_URI . "/images/mslc/questionMark.jpg" ?>">
                    <span class="simpleBoxTooltip">Please reenter your new password.</span>
                </td>
            </tr>
            <tr>
                <td columnspan="3">
                    <a onclick="$('#editPasswordForm').submit()" class="simpleBoxButton">Submit</a>
                    <a href="<?= $this->url(array("controller" => "profile", "action" => "edit")); ?>" target="_self">Cancel</a>
                </td>
            </tr>
        </table>
    </form>
    <?php
    // ********* returned from password edit
    if ($this->success == "true"):
        $session2 = new Zend_Session_Namespace("alert");
        $session2->editPassword = true;
        ?>
        <script>
            $("#currPwd").val("");
            $("#newPwd").val("");
            $("#conNewPwd").val("");
            window.location = "edit";
        </script>
        <?php
    // *********** End of returned from password edit
    elseif ($this->success == 'false'):
        ?>
        <script>
            iknowu_alert("Your new password is identical to current password.");
        </script>
        <?php
    endif;
    ?>

</div>